apiVersion: v1
kind: Service
metadata:
    name: great-expectations-docs
spec:
    selector:
        app: great-expectations-docs
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30010
    type: NodePort
