apiVersion: v1
kind: Service
metadata:
    name: great_expectations_docs
spec:
    selector:
        app: great_expectations_docs
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: ClusterIP
    volume: ./great_expectations/uncommitted/data_docs/local_site:/usr/share/nginx/html
